// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "Iris/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStorage) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorage)(nil).Close))
}

// GetAnalytics mocks base method.
func (m *MockStorage) GetAnalytics(ctx context.Context, shortURL string) (*models.VisitStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalytics", ctx, shortURL)
	ret0, _ := ret[0].(*models.VisitStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalytics indicates an expected call of GetAnalytics.
func (mr *MockStorageMockRecorder) GetAnalytics(ctx, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalytics", reflect.TypeOf((*MockStorage)(nil).GetAnalytics), ctx, shortURL)
}

// GetOriginalURL mocks base method.
func (m *MockStorage) GetOriginalURL(ctx context.Context, shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURL", ctx, shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalURL indicates an expected call of GetOriginalURL.
func (mr *MockStorageMockRecorder) GetOriginalURL(ctx, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURL", reflect.TypeOf((*MockStorage)(nil).GetOriginalURL), ctx, shortURL)
}

// SaveOriginal mocks base method.
func (m *MockStorage) SaveOriginal(ctx context.Context, originalURL string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOriginal", ctx, originalURL)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveOriginal indicates an expected call of SaveOriginal.
func (mr *MockStorageMockRecorder) SaveOriginal(ctx, originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOriginal", reflect.TypeOf((*MockStorage)(nil).SaveOriginal), ctx, originalURL)
}

// SaveShort mocks base method.
func (m *MockStorage) SaveShort(ctx context.Context, id int64, shortURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveShort", ctx, id, shortURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveShort indicates an expected call of SaveShort.
func (mr *MockStorageMockRecorder) SaveShort(ctx, id, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveShort", reflect.TypeOf((*MockStorage)(nil).SaveShort), ctx, id, shortURL)
}

// SaveVisit mocks base method.
func (m *MockStorage) SaveVisit(ctx context.Context, shortURL, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveVisit", ctx, shortURL, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveVisit indicates an expected call of SaveVisit.
func (mr *MockStorageMockRecorder) SaveVisit(ctx, shortURL, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveVisit", reflect.TypeOf((*MockStorage)(nil).SaveVisit), ctx, shortURL, userAgent)
}

// SaveWithAlias mocks base method.
func (m *MockStorage) SaveWithAlias(ctx context.Context, link models.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWithAlias", ctx, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWithAlias indicates an expected call of SaveWithAlias.
func (mr *MockStorageMockRecorder) SaveWithAlias(ctx, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWithAlias", reflect.TypeOf((*MockStorage)(nil).SaveWithAlias), ctx, link)
}
