CREATE TABLE IF NOT EXISTS links (
    id             INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    original_link  TEXT NOT NULL,
    short_link     TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS visits (
    id          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    link_id     INTEGER NOT NULL REFERENCES links(id) ON DELETE CASCADE,
    user_agent  TEXT,
    ip_address  VARCHAR(45),
    visited_at  TIMESTAMP NOT NULL DEFAULT NOW()
);
