// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "Iris/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAnalytics mocks base method.
func (m *MockService) GetAnalytics(ctx context.Context, shortURL string) (*models.VisitStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalytics", ctx, shortURL)
	ret0, _ := ret[0].(*models.VisitStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalytics indicates an expected call of GetAnalytics.
func (mr *MockServiceMockRecorder) GetAnalytics(ctx, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalytics", reflect.TypeOf((*MockService)(nil).GetAnalytics), ctx, shortURL)
}

// GetOriginalURL mocks base method.
func (m *MockService) GetOriginalURL(ctx context.Context, link models.ShortLink) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURL", ctx, link)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalURL indicates an expected call of GetOriginalURL.
func (mr *MockServiceMockRecorder) GetOriginalURL(ctx, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURL", reflect.TypeOf((*MockService)(nil).GetOriginalURL), ctx, link)
}

// SaveVisit mocks base method.
func (m *MockService) SaveVisit(ctx context.Context, shortURL, userAgent string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveVisit", ctx, shortURL, userAgent)
}

// SaveVisit indicates an expected call of SaveVisit.
func (mr *MockServiceMockRecorder) SaveVisit(ctx, shortURL, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveVisit", reflect.TypeOf((*MockService)(nil).SaveVisit), ctx, shortURL, userAgent)
}

// ShortenLink mocks base method.
func (m *MockService) ShortenLink(ctx context.Context, link models.Link) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortenLink", ctx, link)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortenLink indicates an expected call of ShortenLink.
func (mr *MockServiceMockRecorder) ShortenLink(ctx, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortenLink", reflect.TypeOf((*MockService)(nil).ShortenLink), ctx, link)
}
